micronaut-projects/micronaut-aot

aot-api/src/main/java/io/micronaut/aot/MicronautAotOptimizer.java, aot-cli/build.gradle.kts, aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-core/src/main/java/io/micronaut/aot/core/AOTSourceGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/Configuration.java, aot-core/src/main/java/io/micronaut/aot/core/config/SourceGeneratorLoader.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/YamlPropertySourceGenerator.java
This commit changes the default of optimizations from "true" to "false".
In addition, introspection has been added for optimizers which internally
rely on other optimizers which shouldn't be instantiated via the service
loading infrastructure. This lets us document more properly all available
optimizations.
=> Disable all optimizations by default

aot-cli/src/main/java/io/micronaut/aot/cli/Main.java, aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
Without doing this, even if the app throws an exception, the app
exit as if it succeeded.
=> Fix exit code not propagated

aot-cli/src/main/java/io/micronaut/aot/cli/Main.java, aot-core/src/main/java/io/micronaut/aot/core/Configuration.java
Since this is used in Windows paths.
=> Do not use `:` in separator

aot-api/src/main/java/io/micronaut/aot/MicronautAotOptimizer.java, aot-cli/src/main/java/io/micronaut/aot/cli/Main.java, aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-core/src/main/java/io/micronaut/aot/core/AOTModule.java, aot-core/src/main/java/io/micronaut/aot/core/AOTSourceGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/Option.java, aot-core/src/main/java/io/micronaut/aot/core/config/MetadataUtils.java, aot-core/src/main/java/io/micronaut/aot/core/config/SourceGeneratorLoader.java, aot-core/src/main/java/io/micronaut/aot/core/sourcegen/ApplicationContextConfigurerGenerator.java, aot-core/src/test/groovy/io/micronaut/aot/core/sourcegen/ApplicationContextConfigurerGeneratorTest.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/EnvironmentPropertiesSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/KnownMissingTypesSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/MapPropertySourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/PublishersSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/SealedEnvironmentSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/YamlPropertySourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGeneratorTest.groovy, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGeneratorTest.groovy, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/KnownMissingTypesSourceGeneratorTest.groovy, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGeneratorTest.groovy
The id, dependencies, options, subgenerators etc... of AOT modules,
which was static anyway, is now represented using annotations.
This removes suspicious instantiation of generators just for the
purpose of getting metadata.
=> Represent AOT module metadata via annotations

gradle.properties
The fact that it's commented out apparently causes trouble with
GitHub workflows.
=> Remove `bomProperties` from `gradle.properties`

aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-core/src/main/java/io/micronaut/aot/core/codegen/AbstractCodeGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/context/ApplicationContextAnalyzer.java, aot-core/src/testFixtures/groovy/io/micronaut/aot/core/codegen/AbstractSourceGeneratorSpec.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGenerator.java, aot-std-optimizers/src/main/resources/META-INF/services/io.micronaut.aot.core.AOTCodeGenerator, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGeneratorTest.groovy
This commit introduces a new optimization: if `deduceEnvironment(true)`
is set, then we will get the result of the analysis, which is the list
of environment names and packages, and inject them directly in a
generated application context configurer, which itself disables
`deduceEnvironment`.
This means that the deployment environment must be the same as the
build environment.
=> Add optimization for deduce environment

aot-std-optimizers/build.gradle.kts, build-logic/src/main/groovy/io.micronaut.build.internal.aot-module.gradle
This commit fixes the capabilities published for test fixtures,
preventing the use of the `testFixtures(...)` dependency notation.
This is going to be useful once we have an internal plugin to
create AOT modules.
=> Fix incorrect test fixtures capabilities

aot-core/src/main/java/io/micronaut/aot/core/context/ApplicationContextAnalyzer.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
This commit fixes how service loading filters beans. Before the change it was
done service type by service type, ignoring interactions between them. In
practice, a Micronaut `BeanConfiguration` (like an annotated package) may
disable a bean definition (reference), so we cannot generate the list of
services immediately: we have to finish loading all service types, then we
need to perform a check similar to the one done in Micronaut itself, which
filters out beans which are disabled by a specific configuration.
Fixes #25
=> Make sure that disabled configurations are honored

aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/CachedEnvironmentSourceGenerator.java, aot-std-optimizers/src/main/resources/META-INF/services/io.micronaut.aot.core.AOTCodeGenerator, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/CachedEnvironmentSourceGeneratorTest.groovy
The optimization is effectively a _runtime_ optimization, in the sense
that it doesn't take what is at build time as the runtime values.
Fixes #32
This will also require changes to the Gradle plugin for consistency.
=> Rename sealed environment -> cached environment

aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Environments.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGeneratorTest.groovy
This commit introduces a new configuration option (possible.environments)
which lists the names of environments which can be seen. This makes it
possible to load environments for optimized applications too, as long
as the bean requirements do not check for specific environments.
Without this, the only environments which are "seen" by AOT are the
environments which are active when analyzing the context. It means that
it cannot, for example, convert to yaml configuration files which are
for other environments.
By default, if you specify nothing, then the optimizations ARE using
the active environments. If you do specify the option, then it means
that you want to enable the user to specify different environments
at runtime, for example using the `MICRONAUT_ENVIRONMENTS` variable,
even for …
=> Add an option to configure the list of possible environments

aot-api/src/main/java/io/micronaut/aot/MicronautAotOptimizer.java, aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-core/src/main/java/io/micronaut/aot/core/Configuration.java, aot-core/src/main/java/io/micronaut/aot/core/Environments.java, aot-core/src/main/java/io/micronaut/aot/core/config/DefaultConfiguration.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/ConstantPropertySourcesSourceGeneratorTest.groovy
Currently the AOT analysis can be configured to tell the list of
_possible_ environments, for example so that we can convert _all_
configuration files to Java and not just the currently detected
environment. However, it doesn't let the user specify a particular
target environment for analysis. This may be useful when the
environement where the analysis is performed is known to be different
from the deployment environment. In particular, because the analysis
will be done based on bean requirements, having environments
forcefully activated can enable some beans which would otherwise
have been eliminated from the analysis.
To do this the user needs to configure the following property:
`target.environments=lambda`
=> Add an option to "force" a particular environment

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGeneratorTest.groovy
This commit fixes a bug in the GraalVM feature generation: the exclusion
of service loading should only be done if the native service loading
optimization is enabled.
=> Fix GraalVM feature generation

aot-cli/src/main/java/io/micronaut/aot/cli/Main.java, aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy
In practice, the AOT optimizer classpath and the application classpath
are mixed. The fact of putting the AOT optimizer classpath in a separate
argument creates confusion and can cause problems (if the Micronaut
version of AOT is different from the one under test).
Therefore, this commit removes the optimizer classpath option and uses
a single option.
=> Remove optimizer classpath

aot-core/build.gradle.kts, aot-std-optimizers/build.gradle.kts, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGeneratorTest.groovy, aot-std-optimizers/src/test/resources/logback-test1.xml, aot-std-optimizers/src/test/resources/logback-test2.xml, aot-std-optimizers/src/test/resources/logback-test3.xml, aot-std-optimizers/src/test/resources/logback-test4.xml
This commit introduces proper conversion of logback.xml files to Java. For this purpose, it uses logback 1.3. Because it's still in alpha, this isn't ideal. However, the converter can use logback 1.3, while the actual application can use 1.2.x. This requires,
on the Gradle plugin side, to use:
```gradle
dependencies {
aotPlugins("ch.qos.logback:logback-classic:1.3.0-alpha12")
aotPlugins("org.fusesource.jansi:jansi:1.18")
}
```
The code has a sanity check to make sure that this is the case. It's also worth noting that the conversion implies the use of logback classic.
=> Implement logback.xml to Java conversion

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Logback13GeneratorHelper.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGenerator.java
Depending on the JVM, the sanity check that we perform to search
for Joran's model class may not be enough: it is possible that
more classes are eagerly loaded by the VM. To avoid this, we move
the code which is using Joran 1.3 classes into its own class.
=> Fix Joran classloading error if logback 1.3 isn't on classpath

build-logic/src/main/groovy/io.micronaut.build.internal.aot-project.gradle
The POM files generated by Micronaut AOT have 2 different issues:
- `compileOnlyApi` dependencies are exposed as scope compile instead of provided
- test fixture dependencies end up as optional dependencies
In practice, test fixtures are not intended to be consumed from Maven,
so there's no point in "documenting" them as optional. Similarly, the
compile only dependencies should only be used by AOT plugins, which is
only provided by Gradle.
Fixes #74
=> Cleanup generated POM files

aot-cli/src/main/java/io/micronaut/aot/cli/Main.java
This commit fixes how the CLI creates an isolated classloader:
before it wasn't possible to call the CLI without putting the
whole application classpath on the CLI classpath, which defeats
the purpose of the `--classpath` flag.
Now, the CLI can properly be called with just Micronaut AOT on
classpath, then the `--classpath` flag must be provided with
the union of the AOT classpath and the application classpath.
=> Fix classloader isolation

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Logback13GeneratorHelper.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/ParentTag_Tag_Class_Tuple.java
Injects missing class names in ImplicitModel instances taking into account default tag/class associations.
Previously, this was done while parsing the XML whereas starting with logback 1.3.0-alpha14, this step is delegated to model processing.
Future versions of logback might add this injection functionality to avoid code duplication it other processing pipelines.
=> Ceki/logback 1.3.0 alpha14 adaptation

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/DeduceEnvironmentSourceGenerator.java
This commit fixed the way the deduce environment optimization detects
if it should run or not. Previously it would only run if `deduceEnvironment`
was explicitly set to `true`, not if it was using the default.
With this change, if the user didn't say anything or if it's set to true,
then the optimization will run. Otherwise, we do nothing as it will
already be configured to `false`.
=> Fix deduceEnvironment optimization

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/JitStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/KnownMissingTypesSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NativeStaticServiceLoaderSourceGenerator.java
This commit changes the sample values for the "known missing types" and
"service loading" optimizations, so that if the samples are generated,
users get more relevant idea of what should be put as configuration for
those optimizations.
=> Provide meaningful samples

aot-core/src/main/java/io/micronaut/aot/core/codegen/ApplicationContextConfigurerGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/codegen/MapGenerator.java, aot-core/src/test/groovy/io/micronaut/aot/core/codegen/ApplicationContextConfigurerGeneratorTest.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/MapPropertySourceGenerator.java
This commit introduces an internal optimization which exposes new
properties to the application runtime, so that it can determine if
AOT is enabled. An easy way is for an application to define a bean
annotated with `@ConfigurationProperties`:
```java
@ConfigurationProperties("micronaut.aot")
public class AotConfiguration {
private boolean enabled;
private String runtime;
private List<String> optimizations;
...
}
```
The diagnostics that we expose are intentionally limited.
For example, we don't want to expose the whole configuration,
as it would contain entries which are sensitive to the build
environment (absolute paths for example) which would defeat
caching.
=> Expose properties so that an app can determine if AOT is active

aot-cli/src/test/groovy/io/micronaut/aot/cli/CliTest.groovy, aot-core/src/testFixtures/groovy/io/micronaut/aot/core/codegen/AbstractSourceGeneratorSpec.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/NettyPropertiesSourceGenerator.java, aot-std-optimizers/src/main/resources/META-INF/services/io.micronaut.aot.core.AOTCodeGenerator, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/NettyPropertiesSourceGeneratorTest.groovy
This commit introduces a new optimization (id `netty.properties`) which
allows setting the `io.netty.machineId` and `io.netty.processId` system
properties before Netty reads them. Those system properties are used by
Netty in a composite key which is used to compute a channel id.
By default, if the system properties are not set, Netty will compute them,
which involves scanning MAC addresses or using JMX to get the current process
PID, which is expensive (up to 20ms on my machine).
This optimization, if enabled, overrides the system properties at startup,
by generating _random values at application startup_ for both the MAC
address and the PID. This is the default behavior of Netty when it cannot,
for some reason, infer those, so it should be safe.
Alternatively, the optimization allows for …
=> Introduce Netty optimization

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/EnvironmentPropertiesSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/EnvironmentPropertiesSourceGeneratorTest.groovy
=> Divide long EnvironmentPropertiesOptimizationLoader methods to several small methods.

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
This commit adds 3 new service types which optimize service loading. It's worth noting that this commit will not influence what is done by the build plugins, which have to replicate the list independently.
=> Add missing service types

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/Logback14GeneratorHelper.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/LogbackConfigurationSourceGeneratorTest.groovy
This commit fixes the logback to Java converter. While conversion worked, it was actually duplicating logs because the return value of the configurator was wrong and that it triggered the creation of additional configuration from logback.
=> Fix duplicate logging when converting logback to Java

aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java
As this breaks loading of AOT optimized applications. In practice this doesn't require a new release since this is only used for documentation purposes in that project, but it's better like that.
=> Remove ApplicationContextConfigurer from known service types

aot-core/src/main/java/io/micronaut/aot/core/Runtime.java, aot-std-optimizers/build.gradle.kts, aot-std-optimizers/src/configPropsGenerator/java/io/micronaut/aot/config/ConfigPropsGenerator.java, src/main/docs/guide/introduction.adoc, src/main/docs/guide/quickStart.adoc
This commit retrofits the "configuration properties" page to include documentation of the standard optimizations in the Micronaut AOT documentation page.
Here's what is rendered for the configuration properties page now:
=> Improve documentation

aot-core/src/main/java/io/micronaut/aot/core/AOTContext.java, aot-core/src/main/java/io/micronaut/aot/core/codegen/AbstractSingleClassFileGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/codegen/ApplicationContextConfigurerGenerator.java, aot-core/src/main/java/io/micronaut/aot/core/codegen/DelegatingSourceGenerationContext.java, aot-core/src/main/java/io/micronaut/aot/core/context/DefaultSourceGenerationContext.java, aot-core/src/testFixtures/groovy/io/micronaut/aot/core/codegen/AbstractSourceGeneratorSpec.groovy, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/AbstractStaticServiceLoaderSourceGenerator.java, aot-std-optimizers/src/main/java/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGenerator.java, aot-std-optimizers/src/test/groovy/io/micronaut/aot/std/sourcegen/GraalVMOptimizationFeatureSourceGeneratorTest.groovy
This commit updates how Micronaut AOT generates code for GraalVM 22. In 22, the new default is to forbid build time initialization of classes. Each class which is initialized at build time has to be explicitly declared as such. This commit makes it so that classes we generate and know are initialized at build time are added to the `--initialize-at-build-time` option.
While this fixes a lot of cases, we cannot, unfortunately, kwow upfront all the dependencies of the types we initialize at build time, which may _also_ need build time initialization. This means that in some cases, users will have to explicitly add some types to the list (e.g via a `buildArg` in the native binaries Gradle extension).
Ideally, we should move AOT off build time initialization. However, this is not currently …
=> Fix AOT for GraalVM 22
